# ======================================
# Ruff configuration (Python Linter + Formatter)
# ======================================

# --------------------------
# Global configuration
# --------------------------
line-length = 100
target-version = "py311"

# Automatically apply safe fixes when possible
fix = true
show-fixes = true

# --------------------------
# Linting configuration
# --------------------------
[lint]

# Enabled rule categories
# E, W  -> pycodestyle (format & whitespace)
# F     -> pyflakes (logic, unused imports)
# B     -> bugbear (bad practices)
# I     -> import order (isort-like)
# N     -> naming conventions
# S     -> bandit (security)
# PL    -> pylint (complexity & structure)
# PTH   -> pathlib recommendations
# T20   -> print/debug statements
# RUF   -> Ruff-specific enhancements
select = ["E", "W", "F", "B", "I", "N", "S", "PL", "PTH", "T20", "RUF"]

# Ignore overly strict rules
ignore = [
    "E501",  # line too long
    "B008",  # pytest fixtures false positive
]

# --------------------------
# File-specific rule exceptions
# --------------------------
[lint.per-file-ignores]
"tests/**/*.py" = ["S101", "B008", "PLR2004", "T201"]
"__init__.py" = ["F401"]

# --------------------------
# Import sorting
# --------------------------
[lint.isort]
known-first-party = ["src"]
combine-as-imports = true
lines-between-types = 1
force-single-line = false
order-by-type = true

# --------------------------
# Naming conventions (PEP8 + domain exceptions)
# --------------------------
[lint.pep8-naming]
extend-ignore-names = ["TSP", "API", "DTO", "ID", "GA", "PMX", "OX"]

# --------------------------
# Security checks (Bandit)
# --------------------------
[lint.flake8-bandit]
check-typed-exception = true

# --------------------------
# Structural checks (Pylint-like)
# --------------------------
[lint.pylint]
max-branches = 12
max-statements = 50
max-args = 8
max-positional-args = 5

# --------------------------
# Formatter (Ruff formatter, Black-compatible)
# --------------------------
[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
skip-magic-trailing-comma = false
docstring-code-format = true