experiments:
  - name: tsp_ulysses16_ga_population_100_time_10_tournament_0_1_ox_0_9_insert_0_05_elitist_0_1
    runs: 10
    seed_base: 42

    problem:
      name: tsp
      file_path: data/tsplib/ulysses16.tsp
      optimal_results_path: data/optimal_results.json

    algorithm:
      name: ga
      population_size: 100
      crossover_rate: 0.9
      mutation_rate: 0.05
      max_time: 10.0

      # === SELECTION ===
      selection_config:
        name: tournament
        rate: 0.1

      # === CROSSOVER ===
      crossover_config:
        name: ox

      # === MUTATION ===
      mutation_config:
        name: insert

      # === SUCCESSION ===
      succession_config:
        name: elitist
        elite_rate: 0.1


  - name: tsp_ulysses16_ga_population_200_time_10_rank_0_ox_0_9_swap_0_05_steady_state_0_2
    runs: 10
    seed_base: 100

    problem:
      name: tsp
      file_path: data/tsplib/ulysses16.tsp
      optimal_results_path: data/optimal_results.json

    algorithm:
      name: ga
      population_size: 200
      crossover_rate: 0.9
      mutation_rate: 0.05
      max_time: 10.0

      # === SELECTION ===
      selection_config:
        name: rank

      # === CROSSOVER ===
      crossover_config:
        name: ox

      # === MUTATION ===
      mutation_config:
        name: swap

      # === SUCCESSION ===
      succession_config:
        name: steady_state
        replacement_rate: 0.2