sweep:
  - name_prefix: tsp_ulysses16_sweep
    runs: 10
    seed_base: 42

    problem:
      name: tsp
      file_path: data/tsplib/ulysses16.tsp
      optimal_results_path: data/optimal_results.json

    algorithm:
      name: ga
      population_size: [100, 250, 500, 750, 1000]
      crossover_rate: [0.7, 0.8, 0.9, 0.99]
      mutation_rate: [0.01, 0.02, 0.05, 0.1]
      max_time: [2.0]

      # === SELECTION ===
      selection_config:
        - name: tournament
          rate: [0.01, 0.02, 0.05, 0.1]
        - name: roulette
        - name: rank

      # === CROSSOVER ===
      crossover_config:
        name: [ox, cx, pmx]

      # === MUTATION ===
      mutation_config:
        name: [insert, swap]

      # === SUCCESSION ===
      succession_config:
        - name: elitist
          elite_rate: [0.01, 0.02, 0.05, 0.1]
        - name: steady_state
          replacement_rate: [0.01, 0.02, 0.05, 0.1]